#!/usr/local/bin/python
# Visualization
# Tung M. Phan
# California Institute of Technology
# July 17, 2018
import sys
sys.path.append('..') # enable importing modules from an upper directory:
from prepare.helper import *
import matplotlib.animation as animation
import matplotlib.pyplot as plt

fig1 = plt.figure()

fig2 = plt.figure()
#ax = fig.add_axes([0,0.3,1,0.7]) # get rid of white border
ax2 = fig2.add_axes([0,0,1,0.7]) # get rid of white border
fig_get = plt.gca()
fig_get.axes.get_xaxis().set_visible(False)
fig_get.axes.get_yaxis().set_visible(False)
dt = 0.2
monitor_pedestrian_state = 0
background2 = intersection.get_background()

def animate(frame_idx): # update animation by dt
    global background2, monitor_pedestrian_state
    ax2.clear()
    
    monitor_pedestrian_state +=1
    monitor.monitor_pedestrians(monitor_pedestrian_state, background2)
    the_observer = [ax2.imshow(background2)] # update the stage
    background2.close()
    background2 = intersection.get_background()
    print(frame_idx,monitor_pedestrian_state)
    return the_observer


ani = animation.FuncAnimation(fig2, animate, frames=10, interval=0.1, blit=True, repeat=False)
plt.show()
#plt.show()
